---
- name: run
  hosts: all

  vars_files:
    - secrets.yml

  tasks:
    - name: do base
      include_tasks: base/{{ item }}.yml
      loop:
        - tweaks
        - zsh
        - install_docker
        - mount_hdd
        - backup

    - name: deploy containers
      include_tasks: containers/{{ item }}.yml
      loop:
        - traefik
        - dnsmasq
        - homepage
        - home-assistant
        - glances
        - dozzle
        - transmission
        - mosquitto
        - zigbee2mqtt
        - node-red
        - esphome
        - jackett
        - grafana
        - influxdb
        - telegraf
        - redis
        - gitea
        - actual
