- hosts: all

  vars_files:
    - secrets.yml
    
  tasks:

    - name: do base
      include_tasks: "base/{{ item }}.yml"
      loop:
        - tweaks
        - zsh
        - install_docker
        - mount_hdd
        - backup

    - name: deploy containers
      include_tasks: "containers/{{ item }}.yml"
      loop:
        - dnsmasq
        - traefik
        - ntfy
        - homepage
        - glances
        - transmission
        - mosquitto
        - zigbee2mqtt
        - homebridge
        - node-red
        - esphome
        - jackett
        - grafana
        - influxdb
        - gitea
        - actual